name: Merge To Master Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Tree Schema
      run: |
        python3 -m venv env
        source ./env/bin/activate
        python3 -m pip install --upgrade pip
        pip3 install .[test]

    - name: Execute Tests
      run: |
        source ./env/bin/activate
        pytest -vvv
      